---

- name: playbook ping.yml
  hosts: "{{ ansible_limit }}"
  gather_facts: false

  tasks:
  - name: ansible ping
    ping:

  - name: uname -a
    shell:
      cmd: "date; uname -a; cat /etc/os-release"
    register: uname

  - debug:
      var: uname['stdout']