---

- name: playbook server_top_role.yml
  hosts: "{{ ansible_limit }}"
  gather_facts: false
  pre_tasks:
  - name: assert correct git branch
    vars:
      current_git_branch: "{{ lookup('ansible.builtin.pipe', 'git rev-parse --abbrev-ref HEAD') | replace('/','_') }}"
    when: foreman_environment != current_git_branch
    tags:
    - always
    ansible.builtin.fail:
      msg: "curent_git_branch={{current_git_branch}} is not sutable for server with foreman_environment={{foreman_environment}}"
    when: foreman_environment != current_git_branch
  #- setup:
  #  tags:
  #  - always

  tasks:
  - name: include server top role
    include_role:
      role: "{{ top_role }}"

