---

- name: playbook show_vm_vars_and_facts.yml
  hosts: "{{ ansible_limit }}"
  gather_facts: true

  tasks:
    - name: Display all variables for a host
      debug:
        var: hostvars[inventory_hostname] 
