- name: minimal_server/base
  tags:
  - minimal_server/base
  block:
  - import_role:
      role: minimal_server/rundeck_user

  - import_role:
      role: minimal_server/chrony

  - import_role:
      role: minimal_server/defender

  - import_role:
      role: minimal_server/sssd
